[ req ]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = req_ext

[ dn ]
C  = IN
ST = West Bengal
L  = Kolkata
O  = airlegit
OU = DevOps
CN = kafka-master-1.airlegit.com        # Server IP or hostname

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = kafka-master-1.airlegit.com
DNS.2 = KAFKA-Master
IP.1  = 140.238.163.59  
# Server IP
#DNS.1 = mongodb.example.com   # Optional: DNS name if used
