[ req ]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = req_ext

[ dn ]
C  = IN
ST = West Bengal
L  = Kolkata
O  = prm
OU = DevOps
CN = 140.245.22.16        # Server IP or hostname

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
IP.1  = 140.245.22.16     # Server IP
#DNS.1 = mongodb.example.com   # Optional: DNS name if used
