####################################################################
# ROOT CA CONFIGURATION
####################################################################

[ ca ]
default_ca = CA_default

####################################################################
# CA DEFAULT SECTION
####################################################################

[ CA_default ]
dir               = /home/ubuntu/ca/rootca
certs             = $dir/cert
crl_dir           = $dir/crl
new_certs_dir     = $dir/issued_certs
database          = $dir/data/index.dat
serial            = $dir/data/serial.dat
private_key       = $dir/private/rootca.key
certificate       = $dir/cert/rootca.cer
crlnumber         = $dir/data/crl_number
crl               = $dir/crl/rootca.crl

default_md        = sha256
default_days      = 3650
default_crl_days  = 30

policy            = policy_strict
email_in_dn       = no
name_opt          = ca_default
cert_opt          = ca_default
preserve          = no
unique_subject    = no

####################################################################
# POLICY
####################################################################

[ policy_strict ]
countryName             = supplied
stateOrProvinceName     = optional
localityName            = optional
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

####################################################################
# REQUEST SECTION
####################################################################

[ req ]
default_bits        = 4096
distinguished_name  = req_distinguished_name
string_mask         = utf8only
default_md          = sha256
x509_extensions     = v3_ca

[ req_distinguished_name ]
countryName                     = Country Name (2 letter code)
stateOrProvinceName             = State or Province Name
localityName                    = Locality Name
organizationName                = Organization Name
organizationalUnitName          = Organizational Unit Name
commonName                      = Common Name
emailAddress                    = Email Address


countryName_default             = IN
stateOrProvinceName_default     = West Bengal
localityName_default            = Kolkata
organizationName_default        = airlegit
organizationalUnitName_default  = DevOps
commonName_default              = 140.245.22.16
emailAddress_default            = subhrajit@airlegit.com

####################################################################
# ROOT CA EXTENSIONS
####################################################################

[ v3_ca ]
basicConstraints = critical, CA:true, pathlen:2
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
# Optional CRL distribution and AIA if you want clients to know the root
crlDistributionPoints = URI:http://ca.local/rootca.crl
authorityInfoAccess = caIssuers;URI:http://ca.local/rootca.cer

####################################################################
# INTERMEDIATE CA EXTENSIONS
####################################################################

[ v3_intermediate_ca ]
basicConstraints = critical, CA:true, pathlen:0
keyUsage = critical, keyCertSign, cRLSign, digitalSignature
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
crlDistributionPoints = URI:http://ca.local/rootca.crl
authorityInfoAccess = caIssuers;URI:http://ca.local/rootca.cer

####################################################################
# CRL EXTENSIONS
####################################################################

[ crl_ext ]
authorityKeyIdentifier = keyid:always
