[ ca ]
default_ca = CA_default

[ CA_default ]
dir               = /home/ubuntu/ca/rootca
certs             = $dir/cert
crl_dir           = $dir/crl
new_certs_dir     = $dir/issued_certs
database          = $dir/data/index.dat
serial            = $dir/data/serial.dat
private_key       = $dir/private/rootca.key
certificate       = $dir/cert/rootca.cer
crlnumber         = $dir/data/crl_number
crl               = $dir/crl/rootca.crl
crl_extensions    = crl_ext
default_crl_days  = 30
default_md        = sha256
name_opt          = ca_default
cert_opt          = ca_default
default_days      = 3650
preserve          = no
policy            = policy_any
email_in_dn	  = no

[ policy_any ]
countryName             = supplied
stateOrProvinceName     = optional
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ req ]
default_bits        = 2048
distinguished_name  = req_distinguished_name
string_mask         = utf8only
default_md          = sha256
x509_extensions     = v3_ca

[ req_distinguished_name ]
countryName                     = IN
stateOrProvinceName             = West Bengal
localityName                    = Kolkata
0.organizationName              = prm
organizationalUnitName          = devops
commonName                      = 
emailAddress                    = subhrajit@prmfincon.com

countryName_default             = IN
stateOrProvinceName_default     = West Bengal
localityName_default            = Kolkata
0.organizationName_default      = prm
organizationalUnitName_default  = devops
emailAddress_default            = subhrajit@prmfincon.com

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
keyUsage = critical, digitalSignature, cRLSign, keyCertSign
basicConstraints = critical, CA:true, pathlen:2
crlDistributionPoints = URI:http://ca/rootca.crl

[ v3_intermediate_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true, pathlen:0
keyUsage = critical, digitalSignature, cRLSign, keyCertSign
crlDistributionPoints = URI:http://ca/issuingca.crl
authorityInfoAccess = caIssuers;URI:http://ca/rootca.cer

